let Scraper = require('../lib/Scraper');
let ReadConfig = require('../lib/ReadConfig');

let data = {
    "request_conf": {
        "include": ["imperial.craigslist.org", "inlandempire.craigslist.org", "losangeles.craigslist.org", "orangecounty.craigslist.org", "palmsprings.craigslist.org", "sandiego.craigslist.org", "ventura.craigslist.org"],
        "regions": ["socal"],
        "query": "php",
        "srchType": "A",
        "site": "jobs"
    },
    "include": ["imperial.craigslist.org", "inlandempire.craigslist.org", "losangeles.craigslist.org", "orangecounty.craigslist.org", "palmsprings.craigslist.org", "sandiego.craigslist.org", "ventura.craigslist.org"],
    "locations": [
        {
            "state": "AK",
            "type": "alaska",
            "url": "http:\/\/anchorage.craigslist.org\/search\/jjj?",
            "partial": "anchorage.craigslist.org",
            "name": "anchorage \/ mat-su"
        }, {
            "state": "AK",
            "type": "alaska",
            "url": "http:\/\/fairbanks.craigslist.org\/search\/jjj?",
            "partial": "fairbanks.craigslist.org",
            "name": "fairbanks"
        }, {
            "state": "AK",
            "type": "alaska",
            "url": "http:\/\/kenai.craigslist.org\/search\/jjj?",
            "partial": "kenai.craigslist.org",
            "name": "kenai peninsula"
        }, {
            "state": "AK",
            "type": "alaska",
            "url": "http:\/\/juneau.craigslist.org\/search\/jjj?",
            "partial": "juneau.craigslist.org",
            "name": "southeast alaska"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/auburn.craigslist.org\/search\/jjj?",
            "partial": "auburn.craigslist.org",
            "name": "auburn"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/bham.craigslist.org\/search\/jjj?",
            "partial": "bham.craigslist.org",
            "name": "birmingham"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/dothan.craigslist.org\/search\/jjj?",
            "partial": "dothan.craigslist.org",
            "name": "dothan"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/shoals.craigslist.org\/search\/jjj?",
            "partial": "shoals.craigslist.org",
            "name": "florence \/ muscle shoals"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/gadsden.craigslist.org\/search\/jjj?",
            "partial": "gadsden.craigslist.org",
            "name": "gadsden-anniston"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/huntsville.craigslist.org\/search\/jjj?",
            "partial": "huntsville.craigslist.org",
            "name": "huntsville \/ decatur"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/mobile.craigslist.org\/search\/jjj?",
            "partial": "mobile.craigslist.org",
            "name": "mobile"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/montgomery.craigslist.org\/search\/jjj?",
            "partial": "montgomery.craigslist.org",
            "name": "montgomery"
        }, {
            "state": "AL",
            "type": "alabama",
            "url": "http:\/\/tuscaloosa.craigslist.org\/search\/jjj?",
            "partial": "tuscaloosa.craigslist.org",
            "name": "tuscaloosa"
        }, {
            "state": "AR",
            "type": "arkansas",
            "url": "http:\/\/fayar.craigslist.org\/search\/jjj?",
            "partial": "fayar.craigslist.org",
            "name": "fayetteville "
        }, {
            "state": "AR",
            "type": "arkansas",
            "url": "http:\/\/fortsmith.craigslist.org\/search\/jjj?",
            "partial": "fortsmith.craigslist.org",
            "name": "fort smith"
        }, {
            "state": "AR",
            "type": "arkansas",
            "url": "http:\/\/jonesboro.craigslist.org\/search\/jjj?",
            "partial": "jonesboro.craigslist.org",
            "name": "jonesboro"
        }, {
            "state": "AR",
            "type": "arkansas",
            "url": "http:\/\/littlerock.craigslist.org\/search\/jjj?",
            "partial": "littlerock.craigslist.org",
            "name": "little rock"
        }, {
            "state": "AR",
            "type": "arkansas",
            "url": "http:\/\/texarkana.craigslist.org\/search\/jjj?",
            "partial": "texarkana.craigslist.org",
            "name": "texarkana"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/flagstaff.craigslist.org\/search\/jjj?",
            "partial": "flagstaff.craigslist.org",
            "name": "flagstaff \/ sedona"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/mohave.craigslist.org\/search\/jjj?",
            "partial": "mohave.craigslist.org",
            "name": "mohave county"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/phoenix.craigslist.org\/search\/jjj?",
            "partial": "phoenix.craigslist.org",
            "name": "phoenix"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/prescott.craigslist.org\/search\/jjj?",
            "partial": "prescott.craigslist.org",
            "name": "prescott"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/showlow.craigslist.org\/search\/jjj?",
            "partial": "showlow.craigslist.org",
            "name": "show low"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/sierravista.craigslist.org\/search\/jjj?",
            "partial": "sierravista.craigslist.org",
            "name": "sierra vista"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/tucson.craigslist.org\/search\/jjj?",
            "partial": "tucson.craigslist.org",
            "name": "tucson"
        }, {
            "state": "AZ",
            "type": "arizona",
            "url": "http:\/\/yuma.craigslist.org\/search\/jjj?",
            "partial": "yuma.craigslist.org",
            "name": "yuma"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/bakersfield.craigslist.org\/search\/jjj?",
            "partial": "bakersfield.craigslist.org",
            "name": "bakersfield"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/chico.craigslist.org\/search\/jjj?",
            "partial": "chico.craigslist.org",
            "name": "chico"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/fresno.craigslist.org\/search\/jjj?",
            "partial": "fresno.craigslist.org",
            "name": "fresno \/ madera"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/goldcountry.craigslist.org\/search\/jjj?",
            "partial": "goldcountry.craigslist.org",
            "name": "gold country"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/hanford.craigslist.org\/search\/jjj?",
            "partial": "hanford.craigslist.org",
            "name": "hanford-corcoran"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/humboldt.craigslist.org\/search\/jjj?",
            "partial": "humboldt.craigslist.org",
            "name": "humboldt county"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/imperial.craigslist.org\/search\/jjj?",
            "partial": "imperial.craigslist.org",
            "name": "imperial county"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/inlandempire.craigslist.org\/search\/jjj?",
            "partial": "inlandempire.craigslist.org",
            "name": "inland empire"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/losangeles.craigslist.org\/search\/jjj?",
            "partial": "losangeles.craigslist.org",
            "name": "los angeles"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/mendocino.craigslist.org\/search\/jjj?",
            "partial": "mendocino.craigslist.org",
            "name": "mendocino county"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/merced.craigslist.org\/search\/jjj?",
            "partial": "merced.craigslist.org",
            "name": "merced"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/modesto.craigslist.org\/search\/jjj?",
            "partial": "modesto.craigslist.org",
            "name": "modesto"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/monterey.craigslist.org\/search\/jjj?",
            "partial": "monterey.craigslist.org",
            "name": "monterey bay"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/orangecounty.craigslist.org\/search\/jjj?",
            "partial": "orangecounty.craigslist.org",
            "name": "orange county"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/palmsprings.craigslist.org\/search\/jjj?",
            "partial": "palmsprings.craigslist.org",
            "name": "palm springs"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/redding.craigslist.org\/search\/jjj?",
            "partial": "redding.craigslist.org",
            "name": "redding"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/sacramento.craigslist.org\/search\/jjj?",
            "partial": "sacramento.craigslist.org",
            "name": "sacramento"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/sandiego.craigslist.org\/search\/jjj?",
            "partial": "sandiego.craigslist.org",
            "name": "san diego"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/sfbay.craigslist.org\/search\/jjj?",
            "partial": "sfbay.craigslist.org",
            "name": "san francisco bay area"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/slo.craigslist.org\/search\/jjj?",
            "partial": "slo.craigslist.org",
            "name": "san luis obispo"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/santabarbara.craigslist.org\/search\/jjj?",
            "partial": "santabarbara.craigslist.org",
            "name": "santa barbara"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/santamaria.craigslist.org\/search\/jjj?",
            "partial": "santamaria.craigslist.org",
            "name": "santa maria"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/siskiyou.craigslist.org\/search\/jjj?",
            "partial": "siskiyou.craigslist.org",
            "name": "siskiyou county"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/stockton.craigslist.org\/search\/jjj?",
            "partial": "stockton.craigslist.org",
            "name": "stockton"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/susanville.craigslist.org\/search\/jjj?",
            "partial": "susanville.craigslist.org",
            "name": "susanville"
        }, {
            "state": "CA",
            "type": "socal",
            "url": "http:\/\/ventura.craigslist.org\/search\/jjj?",
            "partial": "ventura.craigslist.org",
            "name": "ventura county"
        }, {
            "state": "CA",
            "type": "cencal",
            "url": "http:\/\/visalia.craigslist.org\/search\/jjj?",
            "partial": "visalia.craigslist.org",
            "name": "visalia-tulare"
        }, {
            "state": "CA",
            "type": "norcal",
            "url": "http:\/\/yubasutter.craigslist.org\/search\/jjj?",
            "partial": "yubasutter.craigslist.org",
            "name": "yuba-sutter"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/boulder.craigslist.org\/search\/jjj?",
            "partial": "boulder.craigslist.org",
            "name": "boulder"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/cosprings.craigslist.org\/search\/jjj?",
            "partial": "cosprings.craigslist.org",
            "name": "colorado springs"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/denver.craigslist.org\/search\/jjj?",
            "partial": "denver.craigslist.org",
            "name": "denver"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/eastco.craigslist.org\/search\/jjj?",
            "partial": "eastco.craigslist.org",
            "name": "eastern CO"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/fortcollins.craigslist.org\/search\/jjj?",
            "partial": "fortcollins.craigslist.org",
            "name": "fort collins \/ north CO"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/rockies.craigslist.org\/search\/jjj?",
            "partial": "rockies.craigslist.org",
            "name": "high rockies"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/pueblo.craigslist.org\/search\/jjj?",
            "partial": "pueblo.craigslist.org",
            "name": "pueblo"
        }, {
            "state": "CO",
            "type": "colorado",
            "url": "http:\/\/westslope.craigslist.org\/search\/jjj?",
            "partial": "westslope.craigslist.org",
            "name": "western slope"
        }, {
            "state": "CT",
            "type": "connecticut",
            "url": "http:\/\/newlondon.craigslist.org\/search\/jjj?",
            "partial": "newlondon.craigslist.org",
            "name": "eastern CT"
        }, {
            "state": "CT",
            "type": "connecticut",
            "url": "http:\/\/hartford.craigslist.org\/search\/jjj?",
            "partial": "hartford.craigslist.org",
            "name": "hartford"
        }, {
            "state": "CT",
            "type": "connecticut",
            "url": "http:\/\/newhaven.craigslist.org\/search\/jjj?",
            "partial": "newhaven.craigslist.org",
            "name": "new haven"
        }, {
            "state": "CT",
            "type": "connecticut",
            "url": "http:\/\/nwct.craigslist.org\/search\/jjj?",
            "partial": "nwct.craigslist.org",
            "name": "northwest CT"
        }, {
            "state": "DC",
            "type": "district_of_columbia",
            "url": "http:\/\/washingtondc.craigslist.org\/search\/jjj?",
            "partial": "washingtondc.craigslist.org",
            "name": "washington"
        }, {
            "state": "DE",
            "type": "delaware",
            "url": "http:\/\/delaware.craigslist.org\/search\/jjj?",
            "partial": "delaware.craigslist.org",
            "name": "delaware"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/daytona.craigslist.org\/search\/jjj?",
            "partial": "daytona.craigslist.org",
            "name": "daytona beach"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/keys.craigslist.org\/search\/jjj?",
            "partial": "keys.craigslist.org",
            "name": "florida keys"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/fortlauderdale.craigslist.org\/search\/jjj?",
            "partial": "fortlauderdale.craigslist.org",
            "name": "fort lauderdale"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/fortmyers.craigslist.org\/search\/jjj?",
            "partial": "fortmyers.craigslist.org",
            "name": "ft myers \/ SW florida"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/gainesville.craigslist.org\/search\/jjj?",
            "partial": "gainesville.craigslist.org",
            "name": "gainesville"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/cfl.craigslist.org\/search\/jjj?",
            "partial": "cfl.craigslist.org",
            "name": "heartland florida"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/jacksonville.craigslist.org\/search\/jjj?",
            "partial": "jacksonville.craigslist.org",
            "name": "jacksonville"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/lakeland.craigslist.org\/search\/jjj?",
            "partial": "lakeland.craigslist.org",
            "name": "lakeland"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/lakecity.craigslist.org\/search\/jjj?",
            "partial": "lakecity.craigslist.org",
            "name": "north central FL"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/ocala.craigslist.org\/search\/jjj?",
            "partial": "ocala.craigslist.org",
            "name": "ocala"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/okaloosa.craigslist.org\/search\/jjj?",
            "partial": "okaloosa.craigslist.org",
            "name": "okaloosa \/ walton"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/orlando.craigslist.org\/search\/jjj?",
            "partial": "orlando.craigslist.org",
            "name": "orlando"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/panamacity.craigslist.org\/search\/jjj?",
            "partial": "panamacity.craigslist.org",
            "name": "panama city"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/pensacola.craigslist.org\/search\/jjj?",
            "partial": "pensacola.craigslist.org",
            "name": "pensacola"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/sarasota.craigslist.org\/search\/jjj?",
            "partial": "sarasota.craigslist.org",
            "name": "sarasota-bradenton"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/miami.craigslist.org\/search\/jjj?",
            "partial": "miami.craigslist.org",
            "name": "south florida"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/spacecoast.craigslist.org\/search\/jjj?",
            "partial": "spacecoast.craigslist.org",
            "name": "space coast"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/staugustine.craigslist.org\/search\/jjj?",
            "partial": "staugustine.craigslist.org",
            "name": "st augustine"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/tallahassee.craigslist.org\/search\/jjj?",
            "partial": "tallahassee.craigslist.org",
            "name": "tallahassee"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/tampa.craigslist.org\/search\/jjj?",
            "partial": "tampa.craigslist.org",
            "name": "tampa bay area"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/treasure.craigslist.org\/search\/jjj?",
            "partial": "treasure.craigslist.org",
            "name": "treasure coast"
        }, {
            "state": "FL",
            "type": "florida",
            "url": "http:\/\/westpalmbeach.craigslist.org\/search\/jjj?",
            "partial": "westpalmbeach.craigslist.org",
            "name": "west palm beach"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/albanyga.craigslist.org\/search\/jjj?",
            "partial": "albanyga.craigslist.org",
            "name": "albany "
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/athensga.craigslist.org\/search\/jjj?",
            "partial": "athensga.craigslist.org",
            "name": "athens"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/atlanta.craigslist.org\/search\/jjj?",
            "partial": "atlanta.craigslist.org",
            "name": "atlanta"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/augusta.craigslist.org\/search\/jjj?",
            "partial": "augusta.craigslist.org",
            "name": "augusta"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/brunswick.craigslist.org\/search\/jjj?",
            "partial": "brunswick.craigslist.org",
            "name": "brunswick"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/columbusga.craigslist.org\/search\/jjj?",
            "partial": "columbusga.craigslist.org",
            "name": "columbus "
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/macon.craigslist.org\/search\/jjj?",
            "partial": "macon.craigslist.org",
            "name": "macon \/ warner robins"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/nwga.craigslist.org\/search\/jjj?",
            "partial": "nwga.craigslist.org",
            "name": "northwest GA"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/savannah.craigslist.org\/search\/jjj?",
            "partial": "savannah.craigslist.org",
            "name": "savannah \/ hinesville"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/statesboro.craigslist.org\/search\/jjj?",
            "partial": "statesboro.craigslist.org",
            "name": "statesboro"
        }, {
            "state": "GA",
            "type": "georgia",
            "url": "http:\/\/valdosta.craigslist.org\/search\/jjj?",
            "partial": "valdosta.craigslist.org",
            "name": "valdosta"
        }, {
            "state": "HI",
            "type": "hawaii",
            "url": "http:\/\/honolulu.craigslist.org\/search\/jjj?",
            "partial": "honolulu.craigslist.org",
            "name": "hawaii"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/ames.craigslist.org\/search\/jjj?",
            "partial": "ames.craigslist.org",
            "name": "ames"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/cedarrapids.craigslist.org\/search\/jjj?",
            "partial": "cedarrapids.craigslist.org",
            "name": "cedar rapids"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/desmoines.craigslist.org\/search\/jjj?",
            "partial": "desmoines.craigslist.org",
            "name": "des moines"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/dubuque.craigslist.org\/search\/jjj?",
            "partial": "dubuque.craigslist.org",
            "name": "dubuque"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/fortdodge.craigslist.org\/search\/jjj?",
            "partial": "fortdodge.craigslist.org",
            "name": "fort dodge"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/iowacity.craigslist.org\/search\/jjj?",
            "partial": "iowacity.craigslist.org",
            "name": "iowa city"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/masoncity.craigslist.org\/search\/jjj?",
            "partial": "masoncity.craigslist.org",
            "name": "mason city"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/quadcities.craigslist.org\/search\/jjj?",
            "partial": "quadcities.craigslist.org",
            "name": "quad cities"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/siouxcity.craigslist.org\/search\/jjj?",
            "partial": "siouxcity.craigslist.org",
            "name": "sioux city"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/ottumwa.craigslist.org\/search\/jjj?",
            "partial": "ottumwa.craigslist.org",
            "name": "southeast IA"
        }, {
            "state": "IA",
            "type": "iowa",
            "url": "http:\/\/waterloo.craigslist.org\/search\/jjj?",
            "partial": "waterloo.craigslist.org",
            "name": "waterloo \/ cedar falls"
        }, {
            "state": "ID",
            "type": "idaho",
            "url": "http:\/\/boise.craigslist.org\/search\/jjj?",
            "partial": "boise.craigslist.org",
            "name": "boise"
        }, {
            "state": "ID",
            "type": "idaho",
            "url": "http:\/\/eastidaho.craigslist.org\/search\/jjj?",
            "partial": "eastidaho.craigslist.org",
            "name": "east idaho"
        }, {
            "state": "ID",
            "type": "idaho",
            "url": "http:\/\/lewiston.craigslist.org\/search\/jjj?",
            "partial": "lewiston.craigslist.org",
            "name": "lewiston \/ clarkston"
        }, {
            "state": "ID",
            "type": "idaho",
            "url": "http:\/\/twinfalls.craigslist.org\/search\/jjj?",
            "partial": "twinfalls.craigslist.org",
            "name": "twin falls"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/bn.craigslist.org\/search\/jjj?",
            "partial": "bn.craigslist.org",
            "name": "bloomington-normal"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/chambana.craigslist.org\/search\/jjj?",
            "partial": "chambana.craigslist.org",
            "name": "champaign urbana"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/chicago.craigslist.org\/search\/jjj?",
            "partial": "chicago.craigslist.org",
            "name": "chicago"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/decatur.craigslist.org\/search\/jjj?",
            "partial": "decatur.craigslist.org",
            "name": "decatur"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/lasalle.craigslist.org\/search\/jjj?",
            "partial": "lasalle.craigslist.org",
            "name": "la salle co"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/mattoon.craigslist.org\/search\/jjj?",
            "partial": "mattoon.craigslist.org",
            "name": "mattoon-charleston"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/peoria.craigslist.org\/search\/jjj?",
            "partial": "peoria.craigslist.org",
            "name": "peoria"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/rockford.craigslist.org\/search\/jjj?",
            "partial": "rockford.craigslist.org",
            "name": "rockford"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/carbondale.craigslist.org\/search\/jjj?",
            "partial": "carbondale.craigslist.org",
            "name": "southern illinois"
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/springfieldil.craigslist.org\/search\/jjj?",
            "partial": "springfieldil.craigslist.org",
            "name": "springfield "
        }, {
            "state": "IL",
            "type": "illinois",
            "url": "http:\/\/quincy.craigslist.org\/search\/jjj?",
            "partial": "quincy.craigslist.org",
            "name": "western IL"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/bloomington.craigslist.org\/search\/jjj?",
            "partial": "bloomington.craigslist.org",
            "name": "bloomington"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/evansville.craigslist.org\/search\/jjj?",
            "partial": "evansville.craigslist.org",
            "name": "evansville"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/fortwayne.craigslist.org\/search\/jjj?",
            "partial": "fortwayne.craigslist.org",
            "name": "fort wayne"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/indianapolis.craigslist.org\/search\/jjj?",
            "partial": "indianapolis.craigslist.org",
            "name": "indianapolis"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/kokomo.craigslist.org\/search\/jjj?",
            "partial": "kokomo.craigslist.org",
            "name": "kokomo"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/tippecanoe.craigslist.org\/search\/jjj?",
            "partial": "tippecanoe.craigslist.org",
            "name": "lafayette \/ west lafayette"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/muncie.craigslist.org\/search\/jjj?",
            "partial": "muncie.craigslist.org",
            "name": "muncie \/ anderson"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/richmondin.craigslist.org\/search\/jjj?",
            "partial": "richmondin.craigslist.org",
            "name": "richmond "
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/southbend.craigslist.org\/search\/jjj?",
            "partial": "southbend.craigslist.org",
            "name": "south bend \/ michiana"
        }, {
            "state": "IN",
            "type": "indiana",
            "url": "http:\/\/terrehaute.craigslist.org\/search\/jjj?",
            "partial": "terrehaute.craigslist.org",
            "name": "terre haute"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/lawrence.craigslist.org\/search\/jjj?",
            "partial": "lawrence.craigslist.org",
            "name": "lawrence"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/ksu.craigslist.org\/search\/jjj?",
            "partial": "ksu.craigslist.org",
            "name": "manhattan"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/nwks.craigslist.org\/search\/jjj?",
            "partial": "nwks.craigslist.org",
            "name": "northwest KS"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/salina.craigslist.org\/search\/jjj?",
            "partial": "salina.craigslist.org",
            "name": "salina"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/seks.craigslist.org\/search\/jjj?",
            "partial": "seks.craigslist.org",
            "name": "southeast KS"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/swks.craigslist.org\/search\/jjj?",
            "partial": "swks.craigslist.org",
            "name": "southwest KS"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/topeka.craigslist.org\/search\/jjj?",
            "partial": "topeka.craigslist.org",
            "name": "topeka"
        }, {
            "state": "KS",
            "type": "kansas",
            "url": "http:\/\/wichita.craigslist.org\/search\/jjj?",
            "partial": "wichita.craigslist.org",
            "name": "wichita"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/bgky.craigslist.org\/search\/jjj?",
            "partial": "bgky.craigslist.org",
            "name": "bowling green"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/eastky.craigslist.org\/search\/jjj?",
            "partial": "eastky.craigslist.org",
            "name": "eastern kentucky"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/lexington.craigslist.org\/search\/jjj?",
            "partial": "lexington.craigslist.org",
            "name": "lexington"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/louisville.craigslist.org\/search\/jjj?",
            "partial": "louisville.craigslist.org",
            "name": "louisville"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/owensboro.craigslist.org\/search\/jjj?",
            "partial": "owensboro.craigslist.org",
            "name": "owensboro"
        }, {
            "state": "KY",
            "type": "kentucky",
            "url": "http:\/\/westky.craigslist.org\/search\/jjj?",
            "partial": "westky.craigslist.org",
            "name": "western KY"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/batonrouge.craigslist.org\/search\/jjj?",
            "partial": "batonrouge.craigslist.org",
            "name": "baton rouge"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/cenla.craigslist.org\/search\/jjj?",
            "partial": "cenla.craigslist.org",
            "name": "central louisiana"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/houma.craigslist.org\/search\/jjj?",
            "partial": "houma.craigslist.org",
            "name": "houma"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/lafayette.craigslist.org\/search\/jjj?",
            "partial": "lafayette.craigslist.org",
            "name": "lafayette"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/lakecharles.craigslist.org\/search\/jjj?",
            "partial": "lakecharles.craigslist.org",
            "name": "lake charles"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/monroe.craigslist.org\/search\/jjj?",
            "partial": "monroe.craigslist.org",
            "name": "monroe"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/neworleans.craigslist.org\/search\/jjj?",
            "partial": "neworleans.craigslist.org",
            "name": "new orleans"
        }, {
            "state": "LA",
            "type": "louisiana",
            "url": "http:\/\/shreveport.craigslist.org\/search\/jjj?",
            "partial": "shreveport.craigslist.org",
            "name": "shreveport"
        }, {
            "state": "MA",
            "type": "massachusetts",
            "url": "http:\/\/boston.craigslist.org\/search\/jjj?",
            "partial": "boston.craigslist.org",
            "name": "boston"
        }, {
            "state": "MA",
            "type": "massachusetts",
            "url": "http:\/\/capecod.craigslist.org\/search\/jjj?",
            "partial": "capecod.craigslist.org",
            "name": "cape cod \/ islands"
        }, {
            "state": "MA",
            "type": "massachusetts",
            "url": "http:\/\/southcoast.craigslist.org\/search\/jjj?",
            "partial": "southcoast.craigslist.org",
            "name": "south coast"
        }, {
            "state": "MA",
            "type": "massachusetts",
            "url": "http:\/\/westernmass.craigslist.org\/search\/jjj?",
            "partial": "westernmass.craigslist.org",
            "name": "western massachusetts"
        }, {
            "state": "MA",
            "type": "massachusetts",
            "url": "http:\/\/worcester.craigslist.org\/search\/jjj?",
            "partial": "worcester.craigslist.org",
            "name": "worcester \/ central MA"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/annapolis.craigslist.org\/search\/jjj?",
            "partial": "annapolis.craigslist.org",
            "name": "annapolis"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/baltimore.craigslist.org\/search\/jjj?",
            "partial": "baltimore.craigslist.org",
            "name": "baltimore"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/easternshore.craigslist.org\/search\/jjj?",
            "partial": "easternshore.craigslist.org",
            "name": "eastern shore"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/frederick.craigslist.org\/search\/jjj?",
            "partial": "frederick.craigslist.org",
            "name": "frederick"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/smd.craigslist.org\/search\/jjj?",
            "partial": "smd.craigslist.org",
            "name": "southern maryland"
        }, {
            "state": "MD",
            "type": "maryland",
            "url": "http:\/\/westmd.craigslist.org\/search\/jjj?",
            "partial": "westmd.craigslist.org",
            "name": "western maryland"
        }, {
            "state": "ME",
            "type": "maine",
            "url": "http:\/\/maine.craigslist.org\/search\/jjj?",
            "partial": "maine.craigslist.org",
            "name": "maine"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/annarbor.craigslist.org\/search\/jjj?",
            "partial": "annarbor.craigslist.org",
            "name": "ann arbor"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/battlecreek.craigslist.org\/search\/jjj?",
            "partial": "battlecreek.craigslist.org",
            "name": "battle creek"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/centralmich.craigslist.org\/search\/jjj?",
            "partial": "centralmich.craigslist.org",
            "name": "central michigan"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/detroit.craigslist.org\/search\/jjj?",
            "partial": "detroit.craigslist.org",
            "name": "detroit metro"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/flint.craigslist.org\/search\/jjj?",
            "partial": "flint.craigslist.org",
            "name": "flint"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/grandrapids.craigslist.org\/search\/jjj?",
            "partial": "grandrapids.craigslist.org",
            "name": "grand rapids"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/holland.craigslist.org\/search\/jjj?",
            "partial": "holland.craigslist.org",
            "name": "holland"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/jxn.craigslist.org\/search\/jjj?",
            "partial": "jxn.craigslist.org",
            "name": "jackson "
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/kalamazoo.craigslist.org\/search\/jjj?",
            "partial": "kalamazoo.craigslist.org",
            "name": "kalamazoo"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/lansing.craigslist.org\/search\/jjj?",
            "partial": "lansing.craigslist.org",
            "name": "lansing"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/monroemi.craigslist.org\/search\/jjj?",
            "partial": "monroemi.craigslist.org",
            "name": "monroe "
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/muskegon.craigslist.org\/search\/jjj?",
            "partial": "muskegon.craigslist.org",
            "name": "muskegon"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/nmi.craigslist.org\/search\/jjj?",
            "partial": "nmi.craigslist.org",
            "name": "northern michigan"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/porthuron.craigslist.org\/search\/jjj?",
            "partial": "porthuron.craigslist.org",
            "name": "port huron"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/saginaw.craigslist.org\/search\/jjj?",
            "partial": "saginaw.craigslist.org",
            "name": "saginaw-midland-baycity"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/swmi.craigslist.org\/search\/jjj?",
            "partial": "swmi.craigslist.org",
            "name": "southwest michigan"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/thumb.craigslist.org\/search\/jjj?",
            "partial": "thumb.craigslist.org",
            "name": "the thumb"
        }, {
            "state": "MI",
            "type": "michigan",
            "url": "http:\/\/up.craigslist.org\/search\/jjj?",
            "partial": "up.craigslist.org",
            "name": "upper peninsula"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/bemidji.craigslist.org\/search\/jjj?",
            "partial": "bemidji.craigslist.org",
            "name": "bemidji"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/brainerd.craigslist.org\/search\/jjj?",
            "partial": "brainerd.craigslist.org",
            "name": "brainerd"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/duluth.craigslist.org\/search\/jjj?",
            "partial": "duluth.craigslist.org",
            "name": "duluth \/ superior"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/mankato.craigslist.org\/search\/jjj?",
            "partial": "mankato.craigslist.org",
            "name": "mankato"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/minneapolis.craigslist.org\/search\/jjj?",
            "partial": "minneapolis.craigslist.org",
            "name": "minneapolis \/ st paul"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/rmn.craigslist.org\/search\/jjj?",
            "partial": "rmn.craigslist.org",
            "name": "rochester "
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/marshall.craigslist.org\/search\/jjj?",
            "partial": "marshall.craigslist.org",
            "name": "southwest MN"
        }, {
            "state": "MN",
            "type": "minnesota",
            "url": "http:\/\/stcloud.craigslist.org\/search\/jjj?",
            "partial": "stcloud.craigslist.org",
            "name": "st cloud"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/columbiamo.craigslist.org\/search\/jjj?",
            "partial": "columbiamo.craigslist.org",
            "name": "columbia \/ jeff city"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/joplin.craigslist.org\/search\/jjj?",
            "partial": "joplin.craigslist.org",
            "name": "joplin"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/kansascity.craigslist.org\/search\/jjj?",
            "partial": "kansascity.craigslist.org",
            "name": "kansas city"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/kirksville.craigslist.org\/search\/jjj?",
            "partial": "kirksville.craigslist.org",
            "name": "kirksville"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/loz.craigslist.org\/search\/jjj?",
            "partial": "loz.craigslist.org",
            "name": "lake of the ozarks"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/semo.craigslist.org\/search\/jjj?",
            "partial": "semo.craigslist.org",
            "name": "southeast missouri"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/springfield.craigslist.org\/search\/jjj?",
            "partial": "springfield.craigslist.org",
            "name": "springfield"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/stjoseph.craigslist.org\/search\/jjj?",
            "partial": "stjoseph.craigslist.org",
            "name": "st joseph"
        }, {
            "state": "MO",
            "type": "missouri",
            "url": "http:\/\/stlouis.craigslist.org\/search\/jjj?",
            "partial": "stlouis.craigslist.org",
            "name": "st louis"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/gulfport.craigslist.org\/search\/jjj?",
            "partial": "gulfport.craigslist.org",
            "name": "gulfport \/ biloxi"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/hattiesburg.craigslist.org\/search\/jjj?",
            "partial": "hattiesburg.craigslist.org",
            "name": "hattiesburg"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/jackson.craigslist.org\/search\/jjj?",
            "partial": "jackson.craigslist.org",
            "name": "jackson"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/meridian.craigslist.org\/search\/jjj?",
            "partial": "meridian.craigslist.org",
            "name": "meridian"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/northmiss.craigslist.org\/search\/jjj?",
            "partial": "northmiss.craigslist.org",
            "name": "north mississippi"
        }, {
            "state": "MS",
            "type": "mississippi",
            "url": "http:\/\/natchez.craigslist.org\/search\/jjj?",
            "partial": "natchez.craigslist.org",
            "name": "southwest MS"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/billings.craigslist.org\/search\/jjj?",
            "partial": "billings.craigslist.org",
            "name": "billings"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/bozeman.craigslist.org\/search\/jjj?",
            "partial": "bozeman.craigslist.org",
            "name": "bozeman"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/butte.craigslist.org\/search\/jjj?",
            "partial": "butte.craigslist.org",
            "name": "butte"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/greatfalls.craigslist.org\/search\/jjj?",
            "partial": "greatfalls.craigslist.org",
            "name": "great falls"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/helena.craigslist.org\/search\/jjj?",
            "partial": "helena.craigslist.org",
            "name": "helena"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/kalispell.craigslist.org\/search\/jjj?",
            "partial": "kalispell.craigslist.org",
            "name": "kalispell"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/missoula.craigslist.org\/search\/jjj?",
            "partial": "missoula.craigslist.org",
            "name": "missoula"
        }, {
            "state": "MT",
            "type": "montana",
            "url": "http:\/\/montana.craigslist.org\/search\/jjj?",
            "partial": "montana.craigslist.org",
            "name": "montana (old)"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/asheville.craigslist.org\/search\/jjj?",
            "partial": "asheville.craigslist.org",
            "name": "asheville"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/boone.craigslist.org\/search\/jjj?",
            "partial": "boone.craigslist.org",
            "name": "boone"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/charlotte.craigslist.org\/search\/jjj?",
            "partial": "charlotte.craigslist.org",
            "name": "charlotte"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/eastnc.craigslist.org\/search\/jjj?",
            "partial": "eastnc.craigslist.org",
            "name": "eastern NC"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/fayetteville.craigslist.org\/search\/jjj?",
            "partial": "fayetteville.craigslist.org",
            "name": "fayetteville"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/greensboro.craigslist.org\/search\/jjj?",
            "partial": "greensboro.craigslist.org",
            "name": "greensboro"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/hickory.craigslist.org\/search\/jjj?",
            "partial": "hickory.craigslist.org",
            "name": "hickory \/ lenoir"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/onslow.craigslist.org\/search\/jjj?",
            "partial": "onslow.craigslist.org",
            "name": "jacksonville "
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/outerbanks.craigslist.org\/search\/jjj?",
            "partial": "outerbanks.craigslist.org",
            "name": "outer banks"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/raleigh.craigslist.org\/search\/jjj?",
            "partial": "raleigh.craigslist.org",
            "name": "raleigh \/ durham \/ CH"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/wilmington.craigslist.org\/search\/jjj?",
            "partial": "wilmington.craigslist.org",
            "name": "wilmington"
        }, {
            "state": "NC",
            "type": "north_carolina",
            "url": "http:\/\/winstonsalem.craigslist.org\/search\/jjj?",
            "partial": "winstonsalem.craigslist.org",
            "name": "winston-salem"
        }, {
            "state": "ND",
            "type": "north_dakota",
            "url": "http:\/\/bismarck.craigslist.org\/search\/jjj?",
            "partial": "bismarck.craigslist.org",
            "name": "bismarck"
        }, {
            "state": "ND",
            "type": "north_dakota",
            "url": "http:\/\/fargo.craigslist.org\/search\/jjj?",
            "partial": "fargo.craigslist.org",
            "name": "fargo \/ moorhead"
        }, {
            "state": "ND",
            "type": "north_dakota",
            "url": "http:\/\/grandforks.craigslist.org\/search\/jjj?",
            "partial": "grandforks.craigslist.org",
            "name": "grand forks"
        }, {
            "state": "ND",
            "type": "north_dakota",
            "url": "http:\/\/nd.craigslist.org\/search\/jjj?",
            "partial": "nd.craigslist.org",
            "name": "north dakota"
        }, {
            "state": "NE",
            "type": "nebraska",
            "url": "http:\/\/grandisland.craigslist.org\/search\/jjj?",
            "partial": "grandisland.craigslist.org",
            "name": "grand island"
        }, {
            "state": "NE",
            "type": "nebraska",
            "url": "http:\/\/lincoln.craigslist.org\/search\/jjj?",
            "partial": "lincoln.craigslist.org",
            "name": "lincoln"
        }, {
            "state": "NE",
            "type": "nebraska",
            "url": "http:\/\/northplatte.craigslist.org\/search\/jjj?",
            "partial": "northplatte.craigslist.org",
            "name": "north platte"
        }, {
            "state": "NE",
            "type": "nebraska",
            "url": "http:\/\/omaha.craigslist.org\/search\/jjj?",
            "partial": "omaha.craigslist.org",
            "name": "omaha \/ council bluffs"
        }, {
            "state": "NE",
            "type": "nebraska",
            "url": "http:\/\/scottsbluff.craigslist.org\/search\/jjj?",
            "partial": "scottsbluff.craigslist.org",
            "name": "scottsbluff \/ panhandle"
        }, {
            "state": "NH",
            "type": "new_hampshire",
            "url": "http:\/\/nh.craigslist.org\/search\/jjj?",
            "partial": "nh.craigslist.org",
            "name": "new hampshire"
        }, {
            "state": "NJ",
            "type": "new_jersey",
            "url": "http:\/\/cnj.craigslist.org\/search\/jjj?",
            "partial": "cnj.craigslist.org",
            "name": "central NJ"
        }, {
            "state": "NJ",
            "type": "new_jersey",
            "url": "http:\/\/jerseyshore.craigslist.org\/search\/jjj?",
            "partial": "jerseyshore.craigslist.org",
            "name": "jersey shore"
        }, {
            "state": "NJ",
            "type": "new_jersey",
            "url": "http:\/\/newjersey.craigslist.org\/search\/jjj?",
            "partial": "newjersey.craigslist.org",
            "name": "north jersey"
        }, {
            "state": "NJ",
            "type": "new_jersey",
            "url": "http:\/\/southjersey.craigslist.org\/search\/jjj?",
            "partial": "southjersey.craigslist.org",
            "name": "south jersey"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/albuquerque.craigslist.org\/search\/jjj?",
            "partial": "albuquerque.craigslist.org",
            "name": "albuquerque"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/clovis.craigslist.org\/search\/jjj?",
            "partial": "clovis.craigslist.org",
            "name": "clovis \/ portales"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/farmington.craigslist.org\/search\/jjj?",
            "partial": "farmington.craigslist.org",
            "name": "farmington"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/lascruces.craigslist.org\/search\/jjj?",
            "partial": "lascruces.craigslist.org",
            "name": "las cruces"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/roswell.craigslist.org\/search\/jjj?",
            "partial": "roswell.craigslist.org",
            "name": "roswell \/ carlsbad"
        }, {
            "state": "NM",
            "type": "new_mexico",
            "url": "http:\/\/santafe.craigslist.org\/search\/jjj?",
            "partial": "santafe.craigslist.org",
            "name": "santa fe \/ taos"
        }, {
            "state": "NV",
            "type": "nevada",
            "url": "http:\/\/elko.craigslist.org\/search\/jjj?",
            "partial": "elko.craigslist.org",
            "name": "elko"
        }, {
            "state": "NV",
            "type": "nevada",
            "url": "http:\/\/lasvegas.craigslist.org\/search\/jjj?",
            "partial": "lasvegas.craigslist.org",
            "name": "las vegas"
        }, {
            "state": "NV",
            "type": "nevada",
            "url": "http:\/\/reno.craigslist.org\/search\/jjj?",
            "partial": "reno.craigslist.org",
            "name": "reno \/ tahoe"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/albany.craigslist.org\/search\/jjj?",
            "partial": "albany.craigslist.org",
            "name": "albany"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/binghamton.craigslist.org\/search\/jjj?",
            "partial": "binghamton.craigslist.org",
            "name": "binghamton"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/buffalo.craigslist.org\/search\/jjj?",
            "partial": "buffalo.craigslist.org",
            "name": "buffalo"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/catskills.craigslist.org\/search\/jjj?",
            "partial": "catskills.craigslist.org",
            "name": "catskills"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/chautauqua.craigslist.org\/search\/jjj?",
            "partial": "chautauqua.craigslist.org",
            "name": "chautauqua"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/elmira.craigslist.org\/search\/jjj?",
            "partial": "elmira.craigslist.org",
            "name": "elmira-corning"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/fingerlakes.craigslist.org\/search\/jjj?",
            "partial": "fingerlakes.craigslist.org",
            "name": "finger lakes"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/glensfalls.craigslist.org\/search\/jjj?",
            "partial": "glensfalls.craigslist.org",
            "name": "glens falls"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/hudsonvalley.craigslist.org\/search\/jjj?",
            "partial": "hudsonvalley.craigslist.org",
            "name": "hudson valley"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/ithaca.craigslist.org\/search\/jjj?",
            "partial": "ithaca.craigslist.org",
            "name": "ithaca"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/longisland.craigslist.org\/search\/jjj?",
            "partial": "longisland.craigslist.org",
            "name": "long island"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/newyork.craigslist.org\/search\/jjj?",
            "partial": "newyork.craigslist.org",
            "name": "new york city"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/oneonta.craigslist.org\/search\/jjj?",
            "partial": "oneonta.craigslist.org",
            "name": "oneonta"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/plattsburgh.craigslist.org\/search\/jjj?",
            "partial": "plattsburgh.craigslist.org",
            "name": "plattsburgh-adirondacks"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/potsdam.craigslist.org\/search\/jjj?",
            "partial": "potsdam.craigslist.org",
            "name": "potsdam-canton-massena"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/rochester.craigslist.org\/search\/jjj?",
            "partial": "rochester.craigslist.org",
            "name": "rochester"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/syracuse.craigslist.org\/search\/jjj?",
            "partial": "syracuse.craigslist.org",
            "name": "syracuse"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/twintiers.craigslist.org\/search\/jjj?",
            "partial": "twintiers.craigslist.org",
            "name": "twin tiers NY\/PA"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/utica.craigslist.org\/search\/jjj?",
            "partial": "utica.craigslist.org",
            "name": "utica-rome-oneida"
        }, {
            "state": "NY",
            "type": "new_york",
            "url": "http:\/\/watertown.craigslist.org\/search\/jjj?",
            "partial": "watertown.craigslist.org",
            "name": "watertown"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/akroncanton.craigslist.org\/search\/jjj?",
            "partial": "akroncanton.craigslist.org",
            "name": "akron \/ canton"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/ashtabula.craigslist.org\/search\/jjj?",
            "partial": "ashtabula.craigslist.org",
            "name": "ashtabula"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/athensohio.craigslist.org\/search\/jjj?",
            "partial": "athensohio.craigslist.org",
            "name": "athens "
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/chillicothe.craigslist.org\/search\/jjj?",
            "partial": "chillicothe.craigslist.org",
            "name": "chillicothe"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/cincinnati.craigslist.org\/search\/jjj?",
            "partial": "cincinnati.craigslist.org",
            "name": "cincinnati"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/cleveland.craigslist.org\/search\/jjj?",
            "partial": "cleveland.craigslist.org",
            "name": "cleveland"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/columbus.craigslist.org\/search\/jjj?",
            "partial": "columbus.craigslist.org",
            "name": "columbus"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/dayton.craigslist.org\/search\/jjj?",
            "partial": "dayton.craigslist.org",
            "name": "dayton \/ springfield"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/limaohio.craigslist.org\/search\/jjj?",
            "partial": "limaohio.craigslist.org",
            "name": "lima \/ findlay"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/mansfield.craigslist.org\/search\/jjj?",
            "partial": "mansfield.craigslist.org",
            "name": "mansfield"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/sandusky.craigslist.org\/search\/jjj?",
            "partial": "sandusky.craigslist.org",
            "name": "sandusky"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/toledo.craigslist.org\/search\/jjj?",
            "partial": "toledo.craigslist.org",
            "name": "toledo"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/tuscarawas.craigslist.org\/search\/jjj?",
            "partial": "tuscarawas.craigslist.org",
            "name": "tuscarawas co"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/youngstown.craigslist.org\/search\/jjj?",
            "partial": "youngstown.craigslist.org",
            "name": "youngstown"
        }, {
            "state": "OH",
            "type": "ohio",
            "url": "http:\/\/zanesville.craigslist.org\/search\/jjj?",
            "partial": "zanesville.craigslist.org",
            "name": "zanesville \/ cambridge"
        }, {
            "state": "OK",
            "type": "oklahoma",
            "url": "http:\/\/lawton.craigslist.org\/search\/jjj?",
            "partial": "lawton.craigslist.org",
            "name": "lawton"
        }, {
            "state": "OK",
            "type": "oklahoma",
            "url": "http:\/\/enid.craigslist.org\/search\/jjj?",
            "partial": "enid.craigslist.org",
            "name": "northwest OK"
        }, {
            "state": "OK",
            "type": "oklahoma",
            "url": "http:\/\/oklahomacity.craigslist.org\/search\/jjj?",
            "partial": "oklahomacity.craigslist.org",
            "name": "oklahoma city"
        }, {
            "state": "OK",
            "type": "oklahoma",
            "url": "http:\/\/stillwater.craigslist.org\/search\/jjj?",
            "partial": "stillwater.craigslist.org",
            "name": "stillwater"
        }, {
            "state": "OK",
            "type": "oklahoma",
            "url": "http:\/\/tulsa.craigslist.org\/search\/jjj?",
            "partial": "tulsa.craigslist.org",
            "name": "tulsa"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/bend.craigslist.org\/search\/jjj?",
            "partial": "bend.craigslist.org",
            "name": "bend"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/corvallis.craigslist.org\/search\/jjj?",
            "partial": "corvallis.craigslist.org",
            "name": "corvallis\/albany"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/eastoregon.craigslist.org\/search\/jjj?",
            "partial": "eastoregon.craigslist.org",
            "name": "east oregon"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/eugene.craigslist.org\/search\/jjj?",
            "partial": "eugene.craigslist.org",
            "name": "eugene"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/klamath.craigslist.org\/search\/jjj?",
            "partial": "klamath.craigslist.org",
            "name": "klamath falls"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/medford.craigslist.org\/search\/jjj?",
            "partial": "medford.craigslist.org",
            "name": "medford-ashland"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/oregoncoast.craigslist.org\/search\/jjj?",
            "partial": "oregoncoast.craigslist.org",
            "name": "oregon coast"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/portland.craigslist.org\/search\/jjj?",
            "partial": "portland.craigslist.org",
            "name": "portland"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/roseburg.craigslist.org\/search\/jjj?",
            "partial": "roseburg.craigslist.org",
            "name": "roseburg"
        }, {
            "state": "OR",
            "type": "oregon",
            "url": "http:\/\/salem.craigslist.org\/search\/jjj?",
            "partial": "salem.craigslist.org",
            "name": "salem"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/altoona.craigslist.org\/search\/jjj?",
            "partial": "altoona.craigslist.org",
            "name": "altoona-johnstown"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/chambersburg.craigslist.org\/search\/jjj?",
            "partial": "chambersburg.craigslist.org",
            "name": "cumberland valley"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/erie.craigslist.org\/search\/jjj?",
            "partial": "erie.craigslist.org",
            "name": "erie"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/harrisburg.craigslist.org\/search\/jjj?",
            "partial": "harrisburg.craigslist.org",
            "name": "harrisburg"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/lancaster.craigslist.org\/search\/jjj?",
            "partial": "lancaster.craigslist.org",
            "name": "lancaster"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/allentown.craigslist.org\/search\/jjj?",
            "partial": "allentown.craigslist.org",
            "name": "lehigh valley"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/meadville.craigslist.org\/search\/jjj?",
            "partial": "meadville.craigslist.org",
            "name": "meadville"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/philadelphia.craigslist.org\/search\/jjj?",
            "partial": "philadelphia.craigslist.org",
            "name": "philadelphia"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/pittsburgh.craigslist.org\/search\/jjj?",
            "partial": "pittsburgh.craigslist.org",
            "name": "pittsburgh"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/poconos.craigslist.org\/search\/jjj?",
            "partial": "poconos.craigslist.org",
            "name": "poconos"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/reading.craigslist.org\/search\/jjj?",
            "partial": "reading.craigslist.org",
            "name": "reading"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/scranton.craigslist.org\/search\/jjj?",
            "partial": "scranton.craigslist.org",
            "name": "scranton \/ wilkes-barre"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/pennstate.craigslist.org\/search\/jjj?",
            "partial": "pennstate.craigslist.org",
            "name": "state college"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/williamsport.craigslist.org\/search\/jjj?",
            "partial": "williamsport.craigslist.org",
            "name": "williamsport"
        }, {
            "state": "PA",
            "type": "pennsylvania",
            "url": "http:\/\/york.craigslist.org\/search\/jjj?",
            "partial": "york.craigslist.org",
            "name": "york"
        }, {
            "state": "RI",
            "type": "rhode_island",
            "url": "http:\/\/providence.craigslist.org\/search\/jjj?",
            "partial": "providence.craigslist.org",
            "name": "rhode island"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/charleston.craigslist.org\/search\/jjj?",
            "partial": "charleston.craigslist.org",
            "name": "charleston"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/columbia.craigslist.org\/search\/jjj?",
            "partial": "columbia.craigslist.org",
            "name": "columbia"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/florencesc.craigslist.org\/search\/jjj?",
            "partial": "florencesc.craigslist.org",
            "name": "florence"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/greenville.craigslist.org\/search\/jjj?",
            "partial": "greenville.craigslist.org",
            "name": "greenville \/ upstate"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/hiltonhead.craigslist.org\/search\/jjj?",
            "partial": "hiltonhead.craigslist.org",
            "name": "hilton head"
        }, {
            "state": "SC",
            "type": "south_carolina",
            "url": "http:\/\/myrtlebeach.craigslist.org\/search\/jjj?",
            "partial": "myrtlebeach.craigslist.org",
            "name": "myrtle beach"
        }, {
            "state": "SD",
            "type": "south_dakota",
            "url": "http:\/\/nesd.craigslist.org\/search\/jjj?",
            "partial": "nesd.craigslist.org",
            "name": "northeast SD"
        }, {
            "state": "SD",
            "type": "south_dakota",
            "url": "http:\/\/csd.craigslist.org\/search\/jjj?",
            "partial": "csd.craigslist.org",
            "name": "pierre \/ central SD"
        }, {
            "state": "SD",
            "type": "south_dakota",
            "url": "http:\/\/rapidcity.craigslist.org\/search\/jjj?",
            "partial": "rapidcity.craigslist.org",
            "name": "rapid city \/ west SD"
        }, {
            "state": "SD",
            "type": "south_dakota",
            "url": "http:\/\/siouxfalls.craigslist.org\/search\/jjj?",
            "partial": "siouxfalls.craigslist.org",
            "name": "sioux falls \/ SE SD"
        }, {
            "state": "SD",
            "type": "south_dakota",
            "url": "http:\/\/sd.craigslist.org\/search\/jjj?",
            "partial": "sd.craigslist.org",
            "name": "south dakota"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/chattanooga.craigslist.org\/search\/jjj?",
            "partial": "chattanooga.craigslist.org",
            "name": "chattanooga"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/clarksville.craigslist.org\/search\/jjj?",
            "partial": "clarksville.craigslist.org",
            "name": "clarksville"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/cookeville.craigslist.org\/search\/jjj?",
            "partial": "cookeville.craigslist.org",
            "name": "cookeville"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/jacksontn.craigslist.org\/search\/jjj?",
            "partial": "jacksontn.craigslist.org",
            "name": "jackson  "
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/knoxville.craigslist.org\/search\/jjj?",
            "partial": "knoxville.craigslist.org",
            "name": "knoxville"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/memphis.craigslist.org\/search\/jjj?",
            "partial": "memphis.craigslist.org",
            "name": "memphis"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/nashville.craigslist.org\/search\/jjj?",
            "partial": "nashville.craigslist.org",
            "name": "nashville"
        }, {
            "state": "TN",
            "type": "tennessee",
            "url": "http:\/\/tricities.craigslist.org\/search\/jjj?",
            "partial": "tricities.craigslist.org",
            "name": "tri-cities"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/abilene.craigslist.org\/search\/jjj?",
            "partial": "abilene.craigslist.org",
            "name": "abilene"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/amarillo.craigslist.org\/search\/jjj?",
            "partial": "amarillo.craigslist.org",
            "name": "amarillo"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/austin.craigslist.org\/search\/jjj?",
            "partial": "austin.craigslist.org",
            "name": "austin"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/beaumont.craigslist.org\/search\/jjj?",
            "partial": "beaumont.craigslist.org",
            "name": "beaumont \/ port arthur"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/brownsville.craigslist.org\/search\/jjj?",
            "partial": "brownsville.craigslist.org",
            "name": "brownsville"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/collegestation.craigslist.org\/search\/jjj?",
            "partial": "collegestation.craigslist.org",
            "name": "college station"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/corpuschristi.craigslist.org\/search\/jjj?",
            "partial": "corpuschristi.craigslist.org",
            "name": "corpus christi"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/dallas.craigslist.org\/search\/jjj?",
            "partial": "dallas.craigslist.org",
            "name": "dallas \/ fort worth"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/nacogdoches.craigslist.org\/search\/jjj?",
            "partial": "nacogdoches.craigslist.org",
            "name": "deep east texas"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/delrio.craigslist.org\/search\/jjj?",
            "partial": "delrio.craigslist.org",
            "name": "del rio \/ eagle pass"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/elpaso.craigslist.org\/search\/jjj?",
            "partial": "elpaso.craigslist.org",
            "name": "el paso"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/galveston.craigslist.org\/search\/jjj?",
            "partial": "galveston.craigslist.org",
            "name": "galveston"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/houston.craigslist.org\/search\/jjj?",
            "partial": "houston.craigslist.org",
            "name": "houston"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/killeen.craigslist.org\/search\/jjj?",
            "partial": "killeen.craigslist.org",
            "name": "killeen \/ temple \/ ft hood"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/laredo.craigslist.org\/search\/jjj?",
            "partial": "laredo.craigslist.org",
            "name": "laredo"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/lubbock.craigslist.org\/search\/jjj?",
            "partial": "lubbock.craigslist.org",
            "name": "lubbock"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/mcallen.craigslist.org\/search\/jjj?",
            "partial": "mcallen.craigslist.org",
            "name": "mcallen \/ edinburg"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/odessa.craigslist.org\/search\/jjj?",
            "partial": "odessa.craigslist.org",
            "name": "odessa \/ midland"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/sanangelo.craigslist.org\/search\/jjj?",
            "partial": "sanangelo.craigslist.org",
            "name": "san angelo"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/sanantonio.craigslist.org\/search\/jjj?",
            "partial": "sanantonio.craigslist.org",
            "name": "san antonio"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/sanmarcos.craigslist.org\/search\/jjj?",
            "partial": "sanmarcos.craigslist.org",
            "name": "san marcos"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/bigbend.craigslist.org\/search\/jjj?",
            "partial": "bigbend.craigslist.org",
            "name": "southwest TX"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/texoma.craigslist.org\/search\/jjj?",
            "partial": "texoma.craigslist.org",
            "name": "texoma"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/easttexas.craigslist.org\/search\/jjj?",
            "partial": "easttexas.craigslist.org",
            "name": "tyler \/ east TX"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/victoriatx.craigslist.org\/search\/jjj?",
            "partial": "victoriatx.craigslist.org",
            "name": "victoria "
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/waco.craigslist.org\/search\/jjj?",
            "partial": "waco.craigslist.org",
            "name": "waco"
        }, {
            "state": "TX",
            "type": "texas",
            "url": "http:\/\/wichitafalls.craigslist.org\/search\/jjj?",
            "partial": "wichitafalls.craigslist.org",
            "name": "wichita falls"
        }, {
            "state": "UT",
            "type": "utah",
            "url": "http:\/\/logan.craigslist.org\/search\/jjj?",
            "partial": "logan.craigslist.org",
            "name": "logan"
        }, {
            "state": "UT",
            "type": "utah",
            "url": "http:\/\/ogden.craigslist.org\/search\/jjj?",
            "partial": "ogden.craigslist.org",
            "name": "ogden-clearfield"
        }, {
            "state": "UT",
            "type": "utah",
            "url": "http:\/\/provo.craigslist.org\/search\/jjj?",
            "partial": "provo.craigslist.org",
            "name": "provo \/ orem"
        }, {
            "state": "UT",
            "type": "utah",
            "url": "http:\/\/saltlakecity.craigslist.org\/search\/jjj?",
            "partial": "saltlakecity.craigslist.org",
            "name": "salt lake city"
        }, {
            "state": "UT",
            "type": "utah",
            "url": "http:\/\/stgeorge.craigslist.org\/search\/jjj?",
            "partial": "stgeorge.craigslist.org",
            "name": "st george"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/charlottesville.craigslist.org\/search\/jjj?",
            "partial": "charlottesville.craigslist.org",
            "name": "charlottesville"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/danville.craigslist.org\/search\/jjj?",
            "partial": "danville.craigslist.org",
            "name": "danville"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/fredericksburg.craigslist.org\/search\/jjj?",
            "partial": "fredericksburg.craigslist.org",
            "name": "fredericksburg"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/norfolk.craigslist.org\/search\/jjj?",
            "partial": "norfolk.craigslist.org",
            "name": "hampton roads"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/harrisonburg.craigslist.org\/search\/jjj?",
            "partial": "harrisonburg.craigslist.org",
            "name": "harrisonburg"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/lynchburg.craigslist.org\/search\/jjj?",
            "partial": "lynchburg.craigslist.org",
            "name": "lynchburg"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/blacksburg.craigslist.org\/search\/jjj?",
            "partial": "blacksburg.craigslist.org",
            "name": "new river valley"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/richmond.craigslist.org\/search\/jjj?",
            "partial": "richmond.craigslist.org",
            "name": "richmond"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/roanoke.craigslist.org\/search\/jjj?",
            "partial": "roanoke.craigslist.org",
            "name": "roanoke"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/swva.craigslist.org\/search\/jjj?",
            "partial": "swva.craigslist.org",
            "name": "southwest VA"
        }, {
            "state": "VA",
            "type": "virginia",
            "url": "http:\/\/winchester.craigslist.org\/search\/jjj?",
            "partial": "winchester.craigslist.org",
            "name": "winchester"
        }, {
            "state": "VT",
            "type": "vermont",
            "url": "http:\/\/burlington.craigslist.org\/search\/jjj?",
            "partial": "burlington.craigslist.org",
            "name": "vermont"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/bellingham.craigslist.org\/search\/jjj?",
            "partial": "bellingham.craigslist.org",
            "name": "bellingham"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/kpr.craigslist.org\/search\/jjj?",
            "partial": "kpr.craigslist.org",
            "name": "kennewick-pasco-richland"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/moseslake.craigslist.org\/search\/jjj?",
            "partial": "moseslake.craigslist.org",
            "name": "moses lake"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/olympic.craigslist.org\/search\/jjj?",
            "partial": "olympic.craigslist.org",
            "name": "olympic peninsula"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/pullman.craigslist.org\/search\/jjj?",
            "partial": "pullman.craigslist.org",
            "name": "pullman \/ moscow"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/seattle.craigslist.org\/search\/jjj?",
            "partial": "seattle.craigslist.org",
            "name": "seattle-tacoma"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/skagit.craigslist.org\/search\/jjj?",
            "partial": "skagit.craigslist.org",
            "name": "skagit \/ island \/ SJI"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/spokane.craigslist.org\/search\/jjj?",
            "partial": "spokane.craigslist.org",
            "name": "spokane \/ coeur d'alene"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/wenatchee.craigslist.org\/search\/jjj?",
            "partial": "wenatchee.craigslist.org",
            "name": "wenatchee"
        }, {
            "state": "WA",
            "type": "washington",
            "url": "http:\/\/yakima.craigslist.org\/search\/jjj?",
            "partial": "yakima.craigslist.org",
            "name": "yakima"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/appleton.craigslist.org\/search\/jjj?",
            "partial": "appleton.craigslist.org",
            "name": "appleton-oshkosh-FDL"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/eauclaire.craigslist.org\/search\/jjj?",
            "partial": "eauclaire.craigslist.org",
            "name": "eau claire"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/greenbay.craigslist.org\/search\/jjj?",
            "partial": "greenbay.craigslist.org",
            "name": "green bay"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/janesville.craigslist.org\/search\/jjj?",
            "partial": "janesville.craigslist.org",
            "name": "janesville"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/racine.craigslist.org\/search\/jjj?",
            "partial": "racine.craigslist.org",
            "name": "kenosha-racine"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/lacrosse.craigslist.org\/search\/jjj?",
            "partial": "lacrosse.craigslist.org",
            "name": "la crosse"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/madison.craigslist.org\/search\/jjj?",
            "partial": "madison.craigslist.org",
            "name": "madison"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/milwaukee.craigslist.org\/search\/jjj?",
            "partial": "milwaukee.craigslist.org",
            "name": "milwaukee"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/northernwi.craigslist.org\/search\/jjj?",
            "partial": "northernwi.craigslist.org",
            "name": "northern WI"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/sheboygan.craigslist.org\/search\/jjj?",
            "partial": "sheboygan.craigslist.org",
            "name": "sheboygan"
        }, {
            "state": "WI",
            "type": "wisconsin",
            "url": "http:\/\/wausau.craigslist.org\/search\/jjj?",
            "partial": "wausau.craigslist.org",
            "name": "wausau"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/charlestonwv.craigslist.org\/search\/jjj?",
            "partial": "charlestonwv.craigslist.org",
            "name": "charleston "
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/martinsburg.craigslist.org\/search\/jjj?",
            "partial": "martinsburg.craigslist.org",
            "name": "eastern panhandle"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/huntington.craigslist.org\/search\/jjj?",
            "partial": "huntington.craigslist.org",
            "name": "huntington-ashland"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/morgantown.craigslist.org\/search\/jjj?",
            "partial": "morgantown.craigslist.org",
            "name": "morgantown"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/wheeling.craigslist.org\/search\/jjj?",
            "partial": "wheeling.craigslist.org",
            "name": "northern panhandle"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/parkersburg.craigslist.org\/search\/jjj?",
            "partial": "parkersburg.craigslist.org",
            "name": "parkersburg-marietta"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/swv.craigslist.org\/search\/jjj?",
            "partial": "swv.craigslist.org",
            "name": "southern WV"
        }, {
            "state": "WV",
            "type": "west_virginia",
            "url": "http:\/\/wv.craigslist.org\/search\/jjj?",
            "partial": "wv.craigslist.org",
            "name": "west virginia (old)"
        }, {
            "state": "WY",
            "type": "wyoming",
            "url": "http:\/\/wyoming.craigslist.org\/search\/jjj?",
            "partial": "wyoming.craigslist.org",
            "name": "wyoming"
        }],
    "fields": [{
        "argId": "search_term",
        "argTitle": "Search",
        "argName": "query",
        "argKey": "{query}",
        "argType": "string"
    }, {
        "argId": "search_term_type",
        "argTitle": "Use Title|Use Post:T|A:1|0",
        "argName": "srchType",
        "argKey": "{srchType}",
        "argType": "radio"
    }]
}

let run = (async ()=>{
    let site = 'findjobs';
    let conf = new ReadConfig(`../sites/${site}.locations.xml`);
    await conf.getData();
    let info = conf.getInfo();
    let regions = conf.getRegions();
    let areas = conf.getAreas();
    let locations = conf.getLocations();
    console.log(info, 'info');
    console.log(regions, 'regions');
    console.log(areas, 'areas');
    console.log(locations, 'locations');
    return;
    let scraper = new Scraper(data['request_conf'], data['include'], data['locations'], data['fields']);
    let cl_data = await scraper.fetchData();
    console.log('fetched', cl_data);
});

run();
